name: Create Overleaf tarball

on:
  schedule:
    - cron: '0 21 * * 0'
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.check-version.outputs.should_build }}

    steps:
      - name: Get latest commit
        id: commit
        run: |
          FULL=$(git ls-remote https://github.com/overleaf/overleaf.git HEAD | cut -f1)
          SHORT=${FULL:0:7}
          echo "commit_full=$FULL" >> $GITHUB_OUTPUT
          echo "commit_short=$SHORT" >> $GITHUB_OUTPUT
          
      - name: Clone Overleaf
        run: |
          git clone https://github.com/overleaf/overleaf.git overleaf
          cd overleaf
          git checkout ${{ steps.commit.outputs.commit_full }}

      - name: Get commit date
        id: commit_date
        working-directory: overleaf
        run: |
          COMMIT_DATE="$(git log -1 --format=%cd --date=format:%Y%m%d)"
          echo "commit_date=$COMMIT_DATE" >> $GITHUB_OUTPUT
        
      - name: Define version
        id: version
        run: |
          VERSION="${{ steps.commit_date.outputs.commit_date }}-${{ steps.commit.outputs.commit_short }}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        id: check-version
        shell: bash
        run: |
          TAG="${{ steps.version.outputs.version }}"
          if git ls-remote --exit-code --tags origin "$TAG" ; then
            echo "should_build=false" >> $GITHUB_OUTPUT
          else
            echo "should_build=true" >> $GITHUB_OUTPUT
          fi
        
  build:
    needs: prepare
    if: needs.prepare.outputs.should_build == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:          
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Get npm version from package.json
        id: npm
        run: |
          cd overleaf
          NPM_VERSION=$(jq -r '.engines.npm' package.json)
          echo "npm_version=$NPM_VERSION" >> $GITHUB_OUTPUT

      - name: Install correct npm version
        run: npm install -g npm@${{ steps.npm.outputs.npm_version }}
          
      - name: Install npm packages
        working-directory: overleaf
        run: |
          npm install

      - name: Compile web
        working-directory: overleaf/services/web
        run: |
          npm run precompile-pug
          npm install --include=dev
          npm run webpack:production
          npm run lezer-latex:generate
          npm prune --omit=dev


  release:
    runs-on: ubuntu-latest
    needs: [prepare, build]
    if: needs.prepare.outputs.should_build == 'true'

    permissions:
      contents: write

    steps:

      - name: Prepare release folder
        run: |
          mkdir -p release/services/
          mkdir -p release/libraries/
          mkdir -p release/node_modules/
          mkdir -p release/server-ce/
          
          cp -r overleaf/services/* release/services/
          cp -r overleaf/libraries/* release/libraries/
          cp -r overleaf/node_modules/* release/node_modules/
          cp -r overleaf/server-ce/* release/server-ce/

      - name: Compress Release
        run: tar -czf overleaf_${{ steps.version.outputs.version }}.tar.gz release/

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Overleaf ${{ steps.version.outputs.version }}
          files: overleaf_${{ steps.version.outputs.version }}.tar.gz

        
